Spring:
  application:
    name: separated-service
  data:
    mongodb:
      uri: mongodb+srv://pranshulagarwal:etportal2023@etp.wm53qpg.mongodb.net/?retryWrites=true&w=majority
      database: ETP

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true



