server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: spoc-service
          uri: lb://spoc-service
          predicates:
            - Path=/spoc/**

        - id: separated-service
          uri: lb://separated-service
          predicates:
            - Path=/separated/**

        - id: user-service-auth
          uri: lb://user-service
          predicates:
            - Path=/auth/login/**

        - id: user-service-employee
          uri: lb://user-service
          predicates:
            - Path=/employee/**

        - id: user-service-manager
          uri: lb://user-service
          predicates:
            - Path=/manager/**

        - id: user-service-hr
          uri: lb://user-service
          predicates:
            - Path=/hr/**

        - id: user-service-login
          uri: lb://user-service
          predicates:
            - Path=/auth/login/**

